import type { Product } from "@/lib/products";

export const seedProducts: Product[] = [
  {
    id: "seed-arroz-gallo-1kg",
    name: "Arroz largo fino",
    brand: "Gallo",
    category: "Almacen",
    unit: { label: "1 kg", price: 2400 },
    pack: { qty: 6, label: "pack x6", price: 12900 },
    sortPrice: 2400,
    keywords: ["arroz", "gallo", "largo fino"],
    active: true,
  },
  {
    id: "seed-arroz-luchetti-1kg",
    name: "Arroz parboil",
    brand: "Lucchetti",
    category: "Almacen",
    unit: { label: "1 kg", price: 2200 },
    pack: { qty: 6, label: "pack x6", price: 11800 },
    sortPrice: 2200,
    keywords: ["arroz", "lucchetti", "parboil"],
    active: true,
  },
  {
    id: "seed-atun-la-campagnola",
    name: "Atun al natural",
    brand: "La Campagnola",
    category: "Conservas",
    unit: { label: "170 g", price: 2600 },
    pack: { qty: 3, label: "pack x3", price: 7200 },
    sortPrice: 2600,
    keywords: ["atun", "la campagnola"],
    active: true,
  },
  {
    id: "seed-aceite-natura-900",
    name: "Aceite de girasol",
    brand: "Natura",
    category: "Almacen",
    unit: { label: "900 ml", price: 4600 },
    pack: { qty: 3, label: "pack x3", price: 12900 },
    sortPrice: 4600,
    keywords: ["aceite", "girasol", "natura"],
    active: true,
  },
  {
    id: "seed-gaseosa-coca-225",
    name: "Coca-Cola",
    brand: "Coca-Cola",
    category: "Bebidas",
    unit: { label: "2.25 L", price: 4100 },
    pack: { qty: 2, label: "pack x2", price: 7900 },
    sortPrice: 4100,
    keywords: ["gaseosa", "coca", "coca cola", "cola"],
    active: true,
  },
  {
    id: "seed-gaseosa-sprite-225",
    name: "Sprite",
    brand: "Sprite",
    category: "Bebidas",
    unit: { label: "2.25 L", price: 3900 },
    pack: { qty: 2, label: "pack x2", price: 7500 },
    sortPrice: 3900,
    keywords: ["gaseosa", "sprite", "limon"],
    active: true,
  },
  {
    id: "seed-azucar-ledesma-1kg",
    name: "Azucar",
    brand: "Ledesma",
    category: "Almacen",
    unit: { label: "1 kg", price: 1900 },
    pack: { qty: 3, label: "pack x3", price: 5400 },
    sortPrice: 1900,
    keywords: ["azucar", "ledesma"],
    active: true,
  },
];
